language: generic
sudo: required
service:
    - docker

before_install:
    - docker build -t roryr2l/react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true roryr2l/react-test npm run test

deploy: 
    provider: elasticbeanstalk
    edge: true
    region: "eu-west-2"
    name: "react-test"
    environment: "ReactTest-env"
    bucket_name: "elasticbeanstalk-eu-west-2-503686880813"
    bucket_path: "react-test"
    on:
        branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
